config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  devise_for :users
  resources :users, only: [:index]

  resources :forum_threads do
    resources :posts
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  root 'forum_threads#index'
end

app/models/forum_thread.rb
class ForumThread < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :users, through: :posts
  validates :title, presence: true, length: { minimum: 3 }
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :recipient, class_name: "User"
  belongs_to :actor, class_name: "User"
  belongs_to :notifiable, polymorphic: true

  scope :unread, ->{ where(read_at: nil) }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :forum_thread
  belongs_to :user
  validates :body, presence: true, length: { minimum: 3 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notifications, foreign_key: :recipient_id
  has_many :forum_threads
  has_many :posts
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

 protected

 def configure_devise_permitted_parameters
   registration_params = [:name, :email, :password, :password_confirmation]

   if params[:action] == 'update'
     devise_parameter_sanitizer.for(:account_update) {
       |u| u.permit(registration_params << :current_password)
     }
   elsif params[:action] == 'create'
     devise_parameter_sanitizer.for(:sign_up) {
       |u| u.permit(registration_params)
     }
   end
 end
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :require_permission, only: [:edit, :destroy]

  def index
    @forum_threads = ForumThread.paginate(page: params[:page]).order('id DESC')
  end

  def show
    @forum_thread = ForumThread.friendly.find(params[:id])
  end

  def new
    @forum_thread = current_user.forum_threads.build
  end

  def create
    @forum_thread = current_user.forum_threads.build(forum_thread_params)

    if @forum_thread.save
      redirect_to @forum_thread
    else
      render 'new'
    end
  end

  def edit
    @forum_thread = ForumThread.friendly.find(params[:id])
  end

  def update
    @forum_thread = ForumThread.friendly.find(params[:id])

    if @forum_thread.update(forum_thread_params)
      redirect_to @forum_thread
    else
      render 'edit'
    end
  end

  def destroy
    @forum_thread = ForumThread.friendly.find(params[:id])
    @forum_thread.destroy

    redirect_to forum_threads_path
  end


  private

    def forum_thread_params
      params.require(:forum_thread).permit(:title, :body)
    end

    def require_permission
      if current_user != ForumThread.friendly.find(params[:id]).user
        redirect_to forum_thread_path
        flash[:danger] = "You don't have permission to edit or delete this thread"
      end
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = Notification.where(recipient: current_user).unread
  end

  def mark_as_read
    @notifications = Notification.where(recipient: current_user).unread
    @notifications.update_all(read_at: Time.zone.now)
    render json: {success: true}
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :corrent_user, only: :destroy

  def create
    @forum_thread = ForumThread.find(params[:forum_thread_id])
    @post = @forum_thread.posts.create(post_params)
    @post.user = current_user
    if @post.save

      # Create the notificaation
      (@forum_thread.users.uniq - [current_user]).each do |user|
        Notification.create(recipient: user, actor: current_user, action: "posted", notifiable: @post)
      end

      redirect_to forum_thread_path(@forum_thread)
    else
      render 'forum_threads/show'
    end
  end

  def destroy
    @forum_thread = ForumThread.find(params[:forum_thread_id])
    @post = @forum_thread.posts.find(params[:id])
    @post.destroy
    flash[:success] = "Post deleted"
    redirect_to forum_thread_path(@forum_thread)
  end


  private
    def post_params
      params.require(:post).permit(:body)
    end

    def corrent_user
      @post = current_user.post.find_by(id: params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.paginate(page: params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return the full title on a per_page basis.
  def full_title(page_title = '')
    base_title = "In-App Notification With Rails"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/forum_threads_helper.rb
module ForumThreadsHelper  
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/forum_threads/_form.html.erb
<%= form_for @forum_thread do |f| %>
  <% if @forum_thread.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <%= pluralize(@forum_thread.errors.count, "error") %> prohibited this thread from being saved:
      </div>
      <ul>
        <% @forum_thread.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Thread", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/forum_threads/edit.html.erb
<h1>Edit Thread</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>

app/views/forum_threads/index.html.erb
<% provide(:title) %>
<div id="posts">
  <% @forum_threads.each do |forum_thread| %>
  <div class="post">
    <h2 class="title"><%= link_to forum_thread.title, forum_thread_path(forum_thread) %></h2>
    <p class="date">
      Published at <%= time_ago_in_words(forum_thread.created_at) %> ago by <%= forum_thread.user.name %>
    </p>
  </div>
  <% end %>
  <%= will_paginate %>
</div>

app/views/forum_threads/new.html.erb
<h1>New Thread</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>

app/views/forum_threads/show.html.erb
<div id="post_content">
  <div class="main-content">
    <h1><%= @forum_thread.title %><small> by: <%= @forum_thread.user.name %></small>
    </h1>
    <p>
      <%= @forum_thread.body %>
    </p>
  </div>

  <div id="comments">
      <% @forum_thread.posts.each do |post| %>
      <div class="comment clearfix">
        <div class="content" >
          <p class="comment_content">
            <%= post.body %>
          </p>
          <p class="comment_author">
            <%= post.user.name %>
          </p>
        </div>
        <div class="buttons">
          <%= link_to 'Delete', [post.forum_thread, post],
                       method: :delete,
                       data: { confirm: 'Are you sure?' } %>
        </div>
      </div>

      <% end %>
    </div>
</div>
<br>
<%= form_for([@forum_thread, @forum_thread.posts.build]) do |f| %>
  <div class="form-group">
    <%= f.label :body, 'Post Reply' %>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit Post", class: "btn btn-primary" %>
  </div>
<% end %>

<% if current_user == @forum_thread.user %>
<div class="input-group">
  <div class="input-group-btn">
    <%= link_to "Back to Threads", forum_threads_path, class: "btn btn-default" %>
    <%= link_to "Edit", edit_forum_thread_path(@forum_thread), class: "btn btn-default" %>
    <%= link_to "Delete", forum_thread_path(@forum_thread), class: "btn btn-default", method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
</div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top main_header">
  <div class="container">
    <%= link_to "Notify", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Threads", forum_threads_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">                  <% if user_signed_in? %>
        <li class="nav-item btn-group" data-behavior="notifications" data-notifications='<%= render template: "notifications/index", formats: [:json] %>'>
          <a class="dropdown-toggle nav-link" type="button" data-behavior="notifications-link" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-bell"></span> <span data-behavior="unread-count"></span>
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1" data-behavior="notification-items">
            <!--
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            -->
          </ul>
        </li>
        <li><%= link_to "New Thread", new_forum_thread_path %></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Setting", edit_user_registration_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Log in", new_user_session_path %></li>
      <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </div>


</body>
</html>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li><%= user.name %> | <%= user.email %></li>
  <% end %>
</ul>

<%= will_paginate %>